# Generated by Django 2.1.1 on 2019-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_comment_name', models.CharField(max_length=25)),
                ('time_comment', models.DateTimeField()),
                ('content', models.CharField(max_length=255)),
                ('customer_comment_phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DealedProduct',
            fields=[
                ('dealed_id', models.AutoField(primary_key=True, serialize=False)),
                ('dealed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_product_order', models.IntegerField()),
                ('price_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('sound', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('gurantee', models.CharField(max_length=255)),
                ('promotion', models.IntegerField()),
                ('start_promo', models.DateTimeField()),
                ('end_promo', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
