# Generated by Django 2.1.1 on 2019-03-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_comment_name', models.CharField(max_length=25)),
                ('time_comment', models.DateTimeField()),
                ('content', models.CharField(max_length=255)),
                ('customer_comment_phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DealedProduct',
            fields=[
                ('dealed_id', models.AutoField(primary_key=True, serialize=False)),
                ('dealed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_product_order', models.IntegerField()),
                ('price_order', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('sound', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('gurantee', models.CharField(max_length=255)),
                ('promotion', models.IntegerField()),
                ('start_promo', models.DateTimeField()),
                ('end_promo', models.DateTimeField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=11)),
                ('phone2', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='detailorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='dealedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
