# Generated by Django 2.1.1 on 2019-03-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20190316_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone2',
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
