# Generated by Django 2.1.1 on 2019-04-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190415_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/images/No-img.jpg', upload_to='images/'),
        ),
    ]
