# Generated by Django 2.1.1 on 2019-04-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190419_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
