# Generated by Django 2.1.1 on 2019-04-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
