# Generated by Django 2.1.1 on 2019-04-26 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190425_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealedproduct',
            name='bill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Bill'),
        ),
    ]
