# Generated by Django 2.1.1 on 2019-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_dealedproduct_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
