# Generated by Django 2.1.1 on 2019-04-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190426_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='address',
            field=models.CharField(default='Chưa thanh toán', max_length=255),
        ),
    ]
