# Generated by Django 2.1.1 on 2019-04-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190428_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealedproduct',
            old_name='dealed',
            new_name='number_product_dealed',
        ),
        migrations.RemoveField(
            model_name='dealedproduct',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='detailorder',
            name='price_order',
        ),
        migrations.AlterField(
            model_name='detailorder',
            name='bill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Bill'),
        ),
    ]
