# Generated by Django 2.1.1 on 2019-05-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190429_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sound',
            new_name='CPU',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='hdh',
        ),
    ]
