# Generated by Django 2.1.1 on 2019-05-18 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0023_auto_20190509_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('flash_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_flash', models.DateTimeField()),
                ('end_flash', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transporter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pay_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='transporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Transporter'),
        ),
    ]
