# Generated by Django 2.1.1 on 2019-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190518_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
