# Generated by Django 2.1.1 on 2019-05-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_staff_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashProduct',
            fields=[
                ('flashproduct', models.AutoField(primary_key=True, serialize=False)),
                ('flashsale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.FlashSale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
