# Generated by Django 2.1.1 on 2019-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_cart_num_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealedproduct',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealedproduct',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealedproduct',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
