export const LIST_ALL = 'LIST_ALL';
export const SAVE_TASK = 'SAVE_TASK';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';
export const OPEN_FORM = 'OPEN_FORM';
export const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const FILTER_TABLE = 'FILTER_TABLE';
export const SEARCH = 'SEARCH';
export const SORT = 'SORT';

export const FET_USERS='FET_USERS';
export const FET_USERS_TEACHER='FET_USERS_TEACHER';

export const GET_LIST_FIELD_ONLY_TEACHER='GET_LIST_FIELD_ONLY_TEACHER';

export const ADD_FIELD='ADD_FIELD';
export const DELETE_FIELD='DELETE_FIELD';

export const GET_LIST_TEACHER_AND_TOPIC='GET_LIST_TEACHER_AND_TOPIC';
export const GET_INFO_TEACHER_BY_ID='GET_INFO_TEACHER_BY_ID';

export const REGISTER_TOPIC='REGISTER_TOPIC';
export const SHOW_TOPIC_REGISTER='SHOW_TOPIC_REGISTER';

//teacher
export const TOPIC_OF_TEACHER_BE_REGISTER = 'TOPIC_OF_TEACHER_BE_REGISTER';
export const LOAD_ITEM='LOAD_ITEM';
export const EDIT_ITEM='EDIT_ITEM';
export const TEACHER_LOAD_LIST_HISTORY= 'TEACHER_LOAD_LIST_HISTORY';
export const CHECK_SUBJECT_REGISTERED_OR_NOT = 'CHECK_SUBJECT_REGISTERED_OR_NOT';
//end teacher

//admin
export const ADMIN_GET_INFO_TOPIC_REGISTER='ADMIN_GET_INFO_TOPIC_REGISTER';
export const LOAD_SUBJECT_BE_ACCEPTION= 'LOAD_SUBJECT_BE_ACCEPTION';
export const ACCEPT_TOPIC = 'ACCEPT_TOPIC';
export const LOAD_LIST_HISTORY='LOAD_LIST_HISTORY';
export const LIST_FIELD='LIST_FIELD';
//end admin

export const STUDENT_UPDATE_INFO='STUDENT_UPDATE_INFO';
