// product
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT';
export const GET_LIST_PRODUCT_FILTER_BY_CATEGORY = 'GET_LIST_PRODUCT_FILTER_BY_CATEGORY';

// category
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY';
export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// staff
export const GET_LIST_STAFF = 'GET_LIST_STAFF';
export const EDIT_STAFF_INFO = 'EDIT_STAFF_INFO';
export const DELETE_STAFF = 'DELETE_STAFF';

// customer
export const GET_LIST_CUSTOMER = 'GET_LIST_CUSTOMER';

// staff ship
export const GET_LIST_STAFF_SHIP = 'GET_LIST_STAFF_SHIP';
export const ADD_STAFFSHIP = 'ADD_STAFFSHIP';
export const EDIT_STAFFSHIP = 'EDIT_STAFFSHIP';
export const DELETE_STAFFSHIP = 'DELETE_STAFFSHIP';

// transporter
export const GET_TRANSPORTER = 'GET_TRANSPORTER';