# Generated by Django 2.1.1 on 2019-04-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190319_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff_gun',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
