# Generated by Django 2.1.1 on 2019-06-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190413_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('logging_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_logging', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
